### ISSUE TITLE
Redo the website in VueJS ?

### ISSUE THREAD

**Issue by imalonelynerd** [SquareZeb/VOTV-Secrets-Website#2]
So... This isn't really an issue, more of a request.

I'll try to remake the website using VueJS, as a fun little challenge.

Do you authorize me to do so ?
Thanks in advance !

Nerd

**Comment by SquareZeb** [comment]
I like the idea, but for now I'm going to stick with what I've got since the game is still in its alpha phase-ish. When the game gets fully released I'll allow it.

**Comment by imalonelynerd** [comment]
Noted, do you want me to get an headstart?

**Comment by SquareZeb** [comment]
You can if you want, but dont release it unless I allow.
